// schemagen reflects the recipe types in github.com/zcstarr/roasted/pkg into
// JSON Schema files. It is invoked via `go generate ./pkg` and writes one
// schema per recipe format into the directory given by -out (default ./schemas).
//
// The generated files are committed to the repo so the editor can consume them
// without a build step. `make check-schemas` enforces that they are up to date.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/invopop/jsonschema"

	"github.com/zcstarr/roasted/pkg"
)

const (
	module    = "github.com/zcstarr/roasted"
	idBaseURL = "https://" + module + "/schemas/"
	doNotEdit = "Code generated by tools/schemagen. DO NOT EDIT."
)

type target struct {
	value    any
	filename string
}

func main() {
	out := flag.String("out", "schemas", "directory to write schema files into")
	src := flag.String("src", "pkg", "path to the pkg source directory (for Go-comment descriptions)")
	flag.Parse()

	if err := run(*out, *src); err != nil {
		log.Fatalf("schemagen: %v", err)
	}
}

func run(outDir, srcDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create out dir: %w", err)
	}

	r := &jsonschema.Reflector{}
	if err := r.AddGoComments(module, srcDir); err != nil {
		return fmt.Errorf("add go comments: %w", err)
	}

	targets := []target{
		{value: &pkg.SimpleRecipe{}, filename: "simple-recipe.schema.json"},
		{value: &pkg.OpenRoastRecipe{}, filename: "openroast-recipe.schema.json"},
	}

	for _, t := range targets {
		schema := r.Reflect(t.value)
		schema.ID = jsonschema.ID(idBaseURL + t.filename)
		schema.Comments = doNotEdit

		path := filepath.Join(outDir, t.filename)
		if err := writeSchema(path, schema); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		log.Printf("wrote %s", path)
	}

	return nil
}

func writeSchema(path string, schema *jsonschema.Schema) error {
	buf, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return err
	}
	buf = append(buf, '\n')
	return os.WriteFile(path, buf, 0o644)
}
